-- SQL de siembra generado una sola vez a partir de js/data.js (datos de ejemplo).
-- Ejecutar en Supabase Dashboard > SQL Editor tras supabase/schema.sql.

-- Meses
insert into public.development_months (title, sort_order) values ('Mayo 2026', 0) on conflict (title) do nothing;
insert into public.development_months (title, sort_order) values ('Junio 2026', 1) on conflict (title) do nothing;
insert into public.development_months (title, sort_order) values ('Julio 2026', 2) on conflict (title) do nothing;

-- Tareas
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Mayo 2026'), 'Pixel de medicion', 'Revisar e implementar el pixel correspondiente para medicion, seguimiento o campañas.', 'Preparar la base de medicion para futuras acciones comerciales y de marketing.', 'Completado', 'Media', 'Analitica', false, 0);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Mayo 2026'), 'Mail al receptor del mensaje', 'Enviar un email o notificacion al receptor cuando reciba un nuevo mensaje dentro de la plataforma.', 'Mejora orientada a reducir mensajes perdidos y aumentar respuesta entre usuarios.', 'Completado', 'Alta', 'Mensajes', false, 1);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Mayo 2026'), 'Cambiar flujo de usuario y registro', 'Permitir buscar, filtrar y ver anuncios sin registrarse. Pedir registro solo al contactar o guardar un anuncio.', 'Se recupera el flujo anterior porque reducia friccion inicial.
Objetivo: que el usuario vea valor antes de crear cuenta.', 'Completado', 'Alta', 'Registro', false, 2);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Mayo 2026'), 'Mobile - header sticky y buscador', 'Hacer que el header mobile y el buscador queden fijos durante el scroll, con boton de filtros junto al buscador.', 'Mejora enfocada a navegacion rapida en mobile.', 'Completado', 'Media', 'Responsive', false, 3);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Mayo 2026'), 'Cambiar limites de fotos en anuncios', 'Ajustar limites de fotos por tipo de anuncio: HOMIS 5, habitaciones 10 y vivienda completa 15.', 'Diferencia la necesidad visual segun el tipo de anuncio.', 'Completado', 'Media', 'Publicacion', false, 4);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Mayo 2026'), 'Editar correo y contraseña desde perfil', 'Añadir opciones para editar correo y contraseña desde el perfil, debajo de los datos personales ya editables.', 'Incluye revision de que estuviera subido correctamente.', 'Revisado', 'Media', 'Perfil', false, 5);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Mayo 2026'), 'Checkbox de promociones y email marketing', 'Añadir una casilla no obligatoria durante el registro para ofertas promocionales o email marketing.', 'Si el usuario la marca, debe aparecer como apuntado a newsletter en el panel administrador.', 'Completado', 'Media', 'Marketing', false, 6);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Mayo 2026'), 'Añadir correo en Dashboard Admin', 'Mostrar el correo de la persona en el apartado de estancias del Dashboard Admin, ademas del nombre.', 'Objetivo: permitir contacto y consejos para mejorar anuncios.', 'Completado', 'Media', 'Admin', false, 7);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Mayo 2026'), 'PC - menu lateral sticky e icono de busqueda', 'Hacer sticky el menu lateral en PC y corregir que el icono de busqueda siga visible cuando el menu esta contraido.', 'Actualmente el icono desaparece al contraer el menu.', 'Arrastrada', 'Media', 'Navegacion', true, 8);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Mayo 2026'), 'Campos obligatorios en Publica como HOMI', 'Hacer obligatorios campos clave del flujo de publicacion como HOMI: quien busca, genero, ubicacion, presupuesto, estancia, edad, ocupacion y detalles.', 'Busca mejorar la calidad de los anuncios y evitar fichas incompletas.', 'Arrastrada', 'Alta', 'Publicacion', true, 9);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Mayo 2026'), 'Quitar resaltado incorrecto en anuncios HOMI', 'Quitar el resaltado naranja cuando no haya coincidencias reales o cuando el usuario no haya hecho el test.', 'El naranja solo debe aparecer cuando ambos usuarios coincidan realmente en intereses o comodidades.', 'Arrastrada', 'Alta', 'Matching', true, 10);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Mayo 2026'), 'Boton de publicar anuncio por categoria', 'Añadir un boton de publicar anuncio al lado de cada categoria y abrir popup de anuncios adicionales si el usuario no tiene disponibles.', 'El popup debe seguir una logica similar a los planes de pago.', 'Arrastrada', 'Media', 'Publicacion', true, 11);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Desactivar verificacion por codigo al registrarse', 'Eliminar temporalmente la verificacion mediante codigo OTP en el registro para permitir crear cuenta sin introducir codigo de email.', 'Revisado el 16/06/2026 a las 9:10.
Hecho: registro sin codigo OTP.', 'Revisado', 'Alta', 'Registro', false, 0);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Permitir modificar un anuncio publicado', 'Resolver la edicion de anuncios ya publicados, incluyendo cambios relevantes desde el formulario de modificacion.', 'Revisado el 16/06/2026 a las 9:10.
Hecho: edicion de anuncios resuelta.', 'Revisado', 'Alta', 'Anuncios', false, 1);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Quitar prioridad en Plan Infinito para perfiles Pro', 'Eliminar la prioridad extra de visibilidad de los anuncios del Plan Infinito para perfiles Pro.', 'Los anuncios del Plan Infinito deben actuar como anuncios normales.', 'Completado', 'Alta', 'Planes', false, 2);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Añadir Pro Unlimited desde dashboard', 'Permitir que admin pueda asignar plan Infinity / Pro Unlimited desde la dashboard.', 'Mejora realizada fuera de algunas definiciones iniciales del sprint.', 'Completado', 'Alta', 'Admin', false, 3);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Revisar boton de reportar anuncio', 'Corregir el boton de reportar anuncio para que envie un email con el motivo indicado desde un modal.', 'Revisado el 17/06/2026 a las 08:38.
Hecho: reportar anuncios funcional.', 'Revisado', 'Media', 'Reportes', false, 4);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Mostrar fecha completa del mensaje en el chat', 'Añadir fecha completa junto a la hora para que el usuario identifique claramente cuando fue enviado cada mensaje.', 'Especialmente importante en conversaciones con mensajes de diferentes dias.', 'Completado', 'Media', 'Mensajes', false, 5);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Añadir filtros de mensajes', 'Implementar filtros para mensajes importantes, leidos/no leidos y labels o etiquetas.', 'Hecho: filtro de mensajes añadido.', 'Completado', 'Media', 'Mensajes', false, 6);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Registro e inicio de sesion con Google', 'Investigar e implementar autenticacion mediante cuenta de Google.', 'Hecho: autenticacion mediante Google.', 'Completado', 'Media', 'Autenticacion', false, 7);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Entrar al blog sin autenticar', 'Permitir acceso al blog sin que el usuario tenga que estar autenticado.', 'Extra realizado fuera del listado original.', 'Completado', 'Media', 'Blog', false, 8);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Llevar a registro desde detalles si no esta autenticado', 'Cuando un usuario no autenticado haga clic en detalles del anuncio, llevarlo al registro.', 'Extra realizado fuera del listado original.', 'Completado', 'Media', 'Registro', false, 9);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Cambiar flujo desde landings de habitaciones', 'Al pulsar Ver anuncios, el usuario debe ver tarjetas parcialmente desbloqueadas. El registro/login solo debe aparecer al contactar, ver contacto, ver detalles completos o realizar una accion de mayor intencion.', 'Marcada como urgente en el resumen de pendientes.', 'Arrastrada', 'Alta', 'Landings', true, 10);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Solucionar problema de anuncios adicionales en dashboard', 'Corregir el problema relacionado con anuncios adicionales desde la dashboard.', 'Tarea pendiente de alta prioridad.', 'Arrastrada', 'Alta', 'Dashboard', true, 11);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Campos obligatorios en Publica como HOMI', 'Añadir validaciones obligatorias para campos clave del formulario de publicacion como HOMI.', 'Debe impedir avanzar o publicar si faltan campos requeridos.', 'Arrastrada', 'Alta', 'Publicacion', true, 12);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Quitar resaltado incorrecto en anuncios HOMI', 'Corregir la logica de coincidencias para que el resaltado naranja solo aparezca con coincidencias reales.', 'No debe aparecer si el usuario no hizo el test o no hay match real.', 'Arrastrada', 'Alta', 'Matching', true, 13);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Solucionar error al subir videos a anuncios', 'Revisar y corregir el sistema de subida de videos en anuncios, validando formato, tamaño, almacenamiento y asociacion al anuncio.', 'Pendiente de alta prioridad.', 'Arrastrada', 'Alta', 'Multimedia', true, 14);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Municipios, provincias y mejora de buscador', 'Corregir por que solo aparecen provincias y no municipios, y mejorar buscador y ubicacion de anuncios.', 'Revisar origen de datos, base de datos, API, frontend o filtros.', 'Arrastrada', 'Alta', 'Buscador', true, 15);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'PC - menu lateral sticky e icono de busqueda', 'Mantener sticky el menu lateral en PC y asegurar que el icono de busqueda no desaparezca al contraer el menu.', 'Pendiente de mayo mantenida en junio.', 'Arrastrada', 'Media', 'Navegacion', true, 16);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Revisar responsive del header', 'Detectar en que resolucion se rompe el header y corregir el comportamiento en mobile, tablet y escritorio.', 'Tarea pendiente de media prioridad.', 'Arrastrada', 'Media', 'Responsive', true, 17);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Boton de publicar anuncio por categoria', 'Añadir boton de publicar anuncio junto a cada categoria y gestionar popup si no quedan anuncios disponibles.', 'Debe revisar categorias: habitaciones, viviendas y HOMI.', 'Arrastrada', 'Media', 'Publicacion', true, 18);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Revisar tipo de plan en perfil', 'Corregir incoherencias entre la informacion general del plan y lo mostrado dentro del perfil del usuario.', 'Comparar y corregir datos mostrados.', 'Arrastrada', 'Media', 'Planes', true, 19);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Crear perfil publico para usuarios/profesionales', 'Crear una pagina publica donde se muestren los anuncios activos de un usuario o profesional, similar al funcionamiento de Wallapop.', 'Debe poder accederse desde los anuncios.', 'Arrastrada', 'Media', 'Perfil', true, 20);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Revisar botones de otras preferencias', 'Corregir los botones de otras preferencias dentro de los anuncios para que guarden o apliquen correctamente.', 'Pendiente de media prioridad.', 'Arrastrada', 'Media', 'Preferencias', true, 21);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Mejorar la home page', 'Revisar la estructura y textos de la home para explicar mejor los tipos de anuncio: HOMI, habitacion y vivienda completa.', 'Debe mejorar jerarquia visual y llamadas a la accion.', 'Arrastrada', 'Media', 'Home', true, 22);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Rehacer la descripcion de HOMI', 'Redactar una descripcion mas clara, atractiva y facil de entender para nuevos usuarios.', 'Debe explicar mejor que es un HOMI y encajar con el tono de marca.', 'Arrastrada', 'Media', 'Copy', true, 23);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Permitir subir fotos arrastrandolas', 'Implementar subida drag and drop de fotos con feedback visual, validacion de formato y subida multiple.', 'Mejora de experiencia de usuario.', 'Arrastrada', 'Media', 'Multimedia', true, 24);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Revisar puntos de ruptura responsive', 'Analizar breakpoints y resoluciones problematicas para unificar criterios de maquetacion.', 'Validar en diferentes tamaños de pantalla.', 'Arrastrada', 'Media', 'Responsive', true, 25);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Paginacion: ir al primero o ultimo', 'Añadir comportamiento para que los botones de numeros de pagina en anuncios permitan ir directamente al primero o al ultimo.', 'Pendiente de media prioridad.', 'Arrastrada', 'Media', 'Anuncios', true, 26);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Ordenar articulos del blog por fecha', 'Permitir ordenar los posts del blog por fecha de publicacion, preferiblemente de mas reciente a mas antiguo por defecto.', 'Pendiente de media prioridad.', 'Arrastrada', 'Media', 'Blog', true, 27);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Añadir tiempo de lectura aproximado', 'Calcular automaticamente el tiempo de lectura segun extension del articulo y mostrarlo en tarjeta o dentro del articulo.', 'Ejemplo visual: Tiempo de lectura: 4 min.', 'Arrastrada', 'Media', 'Blog', true, 28);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Sustituir foto de autor por logo HOMI', 'Usar el logo de HOMI como imagen de autor por defecto en articulos, formato 200x200px con fondo #ff7f40.', 'Subir imagen a Supabase.', 'Arrastrada', 'Media', 'Blog', true, 29);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Añadir bio del autor bajo Autor Verificado', 'Añadir una bio del equipo de HOMI bajo el badge Autor Verificado.', 'Texto propuesto: El equipo de HOMI - portal especializado en pisos compartidos fundado en Cuenca.
Escribimos sobre alquiler, convivencia y busqueda de compañeros de piso en España.', 'Arrastrada', 'Media', 'Blog', true, 30);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Crear Linktree en dominio propio', 'Crear una pagina tipo Linktree dentro del dominio propio con enlaces principales de HOMI y diseño adaptado a marca.', 'Optimizada para mobile.', 'Pendiente', 'Baja', 'Dominio', false, 31);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Crear landing page para QR', 'Crear una landing especifica para trafico procedente de QR, clara, directa, mobile first y con llamada a la accion principal.', 'Debe cargar rapido y ser facil de entender.', 'Pendiente', 'Baja', 'Landing', false, 32);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Junio 2026'), 'Enterprise-signup: beneficios arriba y forms abajo', 'En la pagina Como funciona - Enterprise-signup, colocar beneficios arriba y formulario abajo.', 'Pendiente de baja prioridad.', 'Pendiente', 'Baja', 'Landing', false, 33);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Implementar landing de propietarios', 'Implementar la landing para propietarios con enfoque comercial, explicando el valor de HOMI para alquilar con mas compatibilidad y menos friccion.', 'Debe tener tono SaaS moderno y mantener la identidad HOMI.
Priorizar beneficios, confianza, control y contacto.', 'Progreso', 'Alta', 'Landing', false, 0);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Redirigir todos los planes de pago a contacto', 'Todos los planes de pago deben enviar a la pagina de contacto, no a pagos directos ni a landings distintas.', 'La redireccion aplica a planes Pro y al resto de planes de pago.', 'Pendiente', 'Alta', 'Planes', false, 1);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Crear pagina de contacto para propietarios', 'Crear una pagina de contacto diseñada por HOMI, especificada como pagina para propietarios.', 'Debe recoger datos basicos del propietario y tipo de vivienda.
Debe funcionar como paso previo antes de publicar o contratar.', 'Progreso', 'Alta', 'Contacto', false, 2);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Configurar Resend en pagina de contacto', 'Revisar o implementar Resend para enviar correo de confirmacion al propietario tras enviar el formulario.', 'El correo debe confirmar que el mensaje se ha recibido.
Debe indicar que HOMI se pondra en contacto lo antes posible.', 'Pendiente', 'Alta', 'Email', false, 3);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Enviar aviso interno al equipo HOMI', 'Cuando entre un formulario de contacto, enviar un aviso interno al equipo para poder responder al propietario.', 'Debe incluir nombre, email, telefono, ciudad, tipo de vivienda y mensaje.', 'Pendiente', 'Alta', 'Email', false, 4);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Ajustar flujo de usuarios normales', 'Mantener un flujo donde el usuario pueda explorar anuncios parcialmente antes de registrarse y solo se bloquee en acciones de mayor intencion.', 'Registro/login al ver contacto, contactar, guardar o ver detalles completos.
Debe evitar friccion temprana.', 'Progreso', 'Alta', 'Flujo', false, 5);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Corregir flujo desde landings de habitaciones', 'Tarea urgente arrastrada: al pulsar Ver anuncios desde landings de habitaciones, mostrar tarjetas parcialmente desbloqueadas antes de pedir registro.', 'Conecta directamente con la mejora global de flujo de usuario.', 'Arrastrada', 'Alta', 'Landings', true, 6);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Problema de anuncios adicionales en dashboard', 'Resolver el problema de anuncios adicionales desde la dashboard para que el usuario pueda ampliar correctamente segun su plan o necesidad.', 'Debe alinearse con el nuevo flujo de planes/contacto.', 'Arrastrada', 'Alta', 'Dashboard', true, 7);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Campos obligatorios en Publica como HOMI', 'Implementar validaciones obligatorias en el formulario Publica como HOMI para evitar anuncios incompletos.', 'Incluye datos de quien busca, genero, ubicacion, presupuesto, estancia, edad, ocupacion y otros detalles.', 'Arrastrada', 'Alta', 'Publicacion', true, 8);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Quitar resaltado naranja incorrecto', 'Corregir el resaltado naranja para que solo aparezca cuando haya coincidencias reales entre usuarios.', 'No debe mostrarse si no hay test realizado o no hay match real.', 'Arrastrada', 'Alta', 'Matching', true, 9);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Solucionar subida de videos', 'Corregir la subida de videos a anuncios y validar que queden correctamente asociados.', 'Revisar frontend, backend, almacenamiento y validaciones.', 'Arrastrada', 'Alta', 'Multimedia', true, 10);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Mejorar buscador, provincias y municipios', 'Corregir ubicaciones para que aparezcan municipios ademas de provincias y mejorar la precision de busqueda.', 'Tarea clave para experiencia de busqueda.', 'Arrastrada', 'Alta', 'Buscador', true, 11);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Ajustar contenido de landing propietarios', 'Revisar copy de la landing para hablar mas de tranquilidad, control, menos visitas inutiles y perfiles compatibles.', 'Reducir peso de historia si compite con conversion.
Añadir bloque de dolor y bloque de confianza.', 'Pendiente', 'Media', 'Copy', false, 12);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Compactar menciones en medios', 'Mostrar apariciones en medios como prueba social de forma compacta, sin distraer del CTA principal.', 'Formato recomendado: banda de logos o lista breve con enlaces secundarios.', 'Pendiente', 'Media', 'Marca', false, 13);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'CTA unico de propietarios', 'Unificar el CTA principal de la landing de propietarios hacia contacto, evitando mezclar publicar, contratar o ver ventajas.', 'CTA recomendado: Hablar con HOMI o Quiero publicar con ayuda.', 'Pendiente', 'Media', 'Conversion', false, 14);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Añadir FAQs de propietarios', 'Añadir preguntas reales de propietario: comision, quien ve el anuncio, si puede elegir a quien responder, contratos, pagos, inmobiliarias y varias habitaciones.', 'Debe reducir objeciones antes del contacto.', 'Pendiente', 'Media', 'FAQ', false, 15);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Revisar responsive del header', 'Corregir puntos donde el header se rompe en pantallas pequeñas.', 'Validar mobile, tablet y escritorio.', 'Arrastrada', 'Media', 'Responsive', true, 16);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Mejorar home page', 'Explicar mejor los tipos de anuncio en la home: HOMI, habitacion y vivienda completa.', 'Debe ser tan claro como el flujo de publicar anuncio.', 'Arrastrada', 'Media', 'Home', true, 17);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Ordenar articulos y mostrar tiempo de lectura', 'Ordenar articulos por fecha de publicacion y mostrar tiempo de lectura aproximado.', 'Mejora SEO/GEO y experiencia editorial.', 'Arrastrada', 'Media', 'Blog', true, 18);
insert into public.development_tasks (month_id, title, description, details, status, priority, area, is_roadmap, sort_order) values ((select id from public.development_months where title = 'Julio 2026'), 'Enterprise-signup: beneficios arriba y formulario abajo', 'Reordenar la pagina Como funciona - Enterprise-signup con beneficios primero y formulario despues.', 'Pendiente baja, pero relevante para claridad comercial.', 'Pendiente', 'Baja', 'Landing', false, 19);
